[build]
  command = "pip install -r requirements.txt"
  functions = "netlify/functions"
  publish = "public"

[build.environment]
  PYTHON_VERSION = "3.9"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[functions]
  external_node_modules = []
  included_files = ["netlify/functions/api.py"] 