[build]
  command = "pip install -r requirements.txt"
  publish = "."
  functions = "api"

[build.environment]
  PYTHON_VERSION = "3.9"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[headers]]
for = "/*"
[headers.values]
Access-Control-Allow-Origin = "*"
Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
Access-Control-Allow-Headers = "Content-Type"

[functions]
  node_bundler = "esbuild"
  external_node_modules = []
  included_files = ["netlify/functions/api.py"] 