[build]
  base = "/"
  command = "pip install -r requirements.txt"
  publish = "public"
  functions = "functions"

[build.environment]
  PYTHON_VERSION = "3.9"
  NODE_VERSION = "18"
  AWS_LAMBDA_JS_RUNTIME = "nodejs18.x"
  PYTHONPATH = "."
  LANG = "pt_BR.UTF-8"
  NETLIFY_USE_YARN = "true"
  FORCE_COLOR = "1"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[functions]
  directory = "functions"
  node_bundler = "esbuild"
  external_node_modules = ["@sparticuz/chromium"] 