[build]
  command = "pip install -r requirements.txt"
  publish = "."
  functions = "api"

[build.environment]
  PYTHON_VERSION = "3.9"

# Redirecionamento para a documentação Swagger
[[redirects]]
  from = "/docs"
  to = "/.netlify/functions/api/docs"
  status = 200

# Redirecionamento para a documentação ReDoc
[[redirects]]
  from = "/redoc"
  to = "/.netlify/functions/api/redoc"
  status = 200

# Redirecionamento para todos os endpoints da API v1
[[redirects]]
  from = "/api/v1/*"
  to = "/.netlify/functions/api/api/v1/:splat"
  status = 200

# Redirecionamento para a página inicial
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
for = "/*"
[headers.values]
Access-Control-Allow-Origin = "*"
Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
Access-Control-Allow-Headers = "Content-Type, Authorization"

[functions]
  node_bundler = "esbuild"
  external_node_modules = []
  included_files = ["api/api.py", "app/**/*"] 